#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import { Command } from 'commander';import { parseVault } from '../ingest/markdown.js';import { buildSite } from '../build/site.js';import { validateNotes } from '../validate.js';
const program=new Command();program.name('agent-memory').description('Generate semantic HTML and retrieval chunks from Markdown agent memory vaults').version('0.1.0');
program.command('init [dir]').action((dir='memory')=>{fs.mkdirSync(dir,{recursive:true});for(const sub of ['projects','people','decisions','facts','daily','handoffs','procedures'])fs.mkdirSync(path.join(dir,sub),{recursive:true});fs.writeFileSync(path.join(dir,'MEMORY.md'),'---\ntitle: Memory Summary\nvisibility: private\nsensitivity: none\ntags: [summary]\n---\n\n# Memory Summary\n\n## Quick reference\n');console.log(`Initialized ${dir}`)});
program.command('build').option('-s, --source <dir>','source vault','memory').option('-o, --out <dir>','output','dist').option('-m, --mode <mode>','private|public|redacted','private').action(async(o)=>{const notes=await parseVault(o.source);buildSite(notes,o.out,o.mode);console.log(`Built ${notes.length} notes to ${o.out}`)});
program.command('validate').option('-s, --source <dir>','source vault','memory').action(async(o)=>{const notes=await parseVault(o.source);const warnings=validateNotes(notes);warnings.forEach(w=>console.log('WARN',w));if(warnings.length)process.exitCode=1;else console.log('No validation warnings.')});
program.command('serve').option('-o, --out <dir>','output','dist').option('-p, --port <port>','port','4321').action(o=>{const server=http.createServer((req,res)=>{const url=req.url==='/'?'/index.html':req.url||'/index.html';const file=path.join(o.out,decodeURIComponent(url));if(!file.startsWith(path.resolve(o.out))){res.statusCode=403;return res.end('Forbidden')}fs.readFile(file,(err,data)=>{if(err){res.statusCode=404;res.end('Not found')}else{res.end(data)}})});server.listen(Number(o.port),()=>console.log(`Serving ${o.out} on http://localhost:${o.port}`))});
program.command('new <type> <title>').option('-s, --source <dir>','source','memory').action((type,title,o)=>{const dir=path.join(o.source,type.endsWith('s')?type:type+'s');fs.mkdirSync(dir,{recursive:true});const slug=title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');const body=`---\ntitle: "${title}"\ntype: ${type}\nstatus: active\nvisibility: private\nsensitivity: none\ntags: [${type}]\ndate: ${new Date().toISOString().slice(0,10)}\n---\n\n# ${title}\n\n## Summary\n\n## Notes\n`;fs.writeFileSync(path.join(dir,slug+'.md'),body);console.log(`Created ${path.join(dir,slug+'.md')}`)});
program.parse();
