import fs from 'node:fs';
import path from 'node:path';
import type { Note } from '../types.js';
import { normalizePath } from '../util/path.js';

export type EmitTarget =
  | 'agents.md'
  | 'claude.md'
  | 'cursorrules'
  | 'copilot'
  | 'windsurfrules'
  | 'aider'
  | 'llms.txt'
  | 'llms-full.txt';

const TARGET_FILES: Record<EmitTarget, string> = {
  'agents.md': 'AGENTS.md',
  'claude.md': 'CLAUDE.md',
  cursorrules: '.cursorrules',
  copilot: '.github/copilot-instructions.md',
  windsurfrules: '.windsurfrules',
  aider: '.aider.conf.yml',
  'llms.txt': 'llms.txt',
  'llms-full.txt': 'llms-full.txt',
};

export function emitFilename(target: EmitTarget): string {
  return TARGET_FILES[target];
}

export function validTargets(): EmitTarget[] {
  return Object.keys(TARGET_FILES) as EmitTarget[];
}

interface EmitContext {
  notes: Note[];
  title: string;
  description?: string;
}

function instructionNotes(notes: Note[]): Note[] {
  // Treat MEMORY.md + any note with type=instruction|procedure|standard as core context.
  return notes.filter((n) => {
    const t = String(n.meta?.type || '').toLowerCase();
    const isCore = /^memory\.md$/i.test(path.basename(n.sourcePath)) || /^memory$/i.test(n.title);
    return isCore || t === 'instruction' || t === 'procedure' || t === 'standard' || t === 'rule';
  });
}

function renderCommonContent(ctx: EmitContext): string {
  const lines: string[] = [];
  lines.push(`# ${ctx.title}`);
  lines.push('');
  if (ctx.description) {
    lines.push(ctx.description);
    lines.push('');
  }

  const core = instructionNotes(ctx.notes);
  if (core.length) {
    lines.push('## Core instructions');
    for (const n of core) {
      lines.push('');
      lines.push(`### ${n.title}`);
      lines.push('');
      lines.push(n.body);
    }
    lines.push('');
  }

  // Inventory at the end for retrieval planning.
  const byCat = new Map<string, Note[]>();
  for (const n of ctx.notes) {
    byCat.set(n.category, [...(byCat.get(n.category) || []), n]);
  }
  lines.push('## Memory inventory');
  for (const [cat, items] of byCat) {
    lines.push('');
    lines.push(`### ${cat} (${items.length})`);
    for (const n of items) {
      const updated = n.updated_at ? ` _(updated ${n.updated_at.slice(0, 10)})_` : '';
      lines.push(`- **${n.title}** — \`${n.relPath}\`${updated}`);
    }
  }
  return lines.join('\n');
}

function renderTarget(target: EmitTarget, ctx: EmitContext): string {
  const common = renderCommonContent(ctx);
  switch (target) {
    case 'agents.md':
      return `<!-- AGENTS.md — generated by agent-memory-site. Edit source notes, not this file. -->\n\n${common}\n`;
    case 'claude.md':
      return `<!-- CLAUDE.md — generated by agent-memory-site. See https://github.com/nikopastore/agent-memory-site -->\n\n${common}\n`;
    case 'copilot':
      return `<!-- copilot-instructions.md — generated by agent-memory-site -->\n\n${common}\n`;
    case 'cursorrules':
      // .cursorrules is plain text rules without markdown headers. Strip headers but keep structure.
      return common.replace(/^#{1,6}\s+/gm, '').trim() + '\n';
    case 'windsurfrules':
      return common + '\n';
    case 'aider': {
      // Minimal aider config that pins read-only context to the generated llms.txt
      return `# .aider.conf.yml — generated by agent-memory-site\nread:\n  - llms.txt\n`;
    }
    case 'llms.txt': {
      const lines: string[] = [];
      lines.push(`# ${ctx.title}`);
      lines.push('');
      if (ctx.description) {
        lines.push(`> ${ctx.description}`);
        lines.push('');
      }
      const byCat = new Map<string, Note[]>();
      for (const n of ctx.notes) byCat.set(n.category, [...(byCat.get(n.category) || []), n]);
      for (const [cat, items] of byCat) {
        lines.push(`## ${cat}`);
        for (const n of items) lines.push(`- [${n.title}](notes/${n.slug}.html)`);
        lines.push('');
      }
      return lines.join('\n');
    }
    case 'llms-full.txt': {
      const parts: string[] = [];
      for (const n of ctx.notes) {
        parts.push(`# ${n.title}`);
        parts.push(`<!-- doc_id: ${n.id} category: ${n.category} updated: ${n.updated_at || 'unknown'} -->`);
        parts.push('');
        parts.push(n.body);
        parts.push('');
        parts.push('---');
        parts.push('');
      }
      return parts.join('\n');
    }
  }
}

export interface EmitResult {
  target: EmitTarget;
  outPath: string;
  bytes: number;
}

export function emit(target: EmitTarget, ctx: EmitContext, outDir: string = '.'): EmitResult {
  const rel = TARGET_FILES[target];
  const full = path.resolve(outDir, rel);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  const content = renderTarget(target, ctx);
  fs.writeFileSync(full, content);
  return { target, outPath: normalizePath(full), bytes: Buffer.byteLength(content, 'utf8') };
}
